# Generated by Django 4.2.7 on 2024-01-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_alter_students_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='code',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
