# Generated by Django 4.2.7 on 2024-01-31 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_alter_students_code_alter_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contact',
            field=models.IntegerField(unique=True),
        ),
    ]
