# Generated by Django 4.2.7 on 2024-02-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0008_alter_books_status_alter_borrow_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='book_id',
            field=models.IntegerField(unique=True),
        ),
    ]
