# Generated by Django 4.2.7 on 2024-02-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_books_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='quantity',
        ),
    ]
